"""Generate the TikZ figures in the note from the compiler's own output."""
import numpy as np, pyzx as zx, zxemit as E, zxtikz as Z, exp1_convergent as X1

r2 = 1/np.sqrt(2)
frag = []

def emit(name, tikz):
    frag.append(f"% ---- {name} (generated by mkfigs.py) ----")
    frag.append("\\newcommand{\\" + name + "}{%\n" + tikz + "}")
    frag.append("")

# 1. the emitted one-step diagram for the minimal closed diamond
g = X1.cap(X1.build(r2, -r2), "X")
names = {}
for v in g.vertices():
    if g.type(v) == 0:
        names[v] = {0: "$s$", 1: "$a$", 2: "$B$"}.get(int(g.qubit(v)), "")
emit("figemitted", Z.to_tikz(g, xscale=1.55, yscale=1.25,
         row_labels={0.0: "$s$", 1.0: "$a$", 2.0: "$B$"}))

# 2. the race, reduced, under each cap
for cap, tag in [("X", "figracex"), (0, "figracez")]:
    _, order, gg, h = Z.race_amplitudes(r2, r2, cap)
    nm = {}
    for v in h.vertices():
        if h.type(v) == 0:
            nm[v] = {0: "$s$", 1: "$a$", 2: "$b$"}.get(int(round(float(h.qubit(v)))), "")
    emit(tag, Z.to_tikz(h, xscale=1.5, yscale=1.25,
         row_labels={0.0: "$s$", 1.0: "$a$", 2.0: "$b$"}))
    print(tag, h.num_vertices(), "v", h.num_edges(), "e")

open("figures.tex", "w").write("\n".join(frag) + "\n")
print("wrote figures.tex")
