//! The spatial--behavioural logic.
//!
//! Generated, not designed: one structural connective per term former of the
//! signature, one context-labelled modality per rewrite rule together with a
//! choice of redex position, a propositional layer, and two additions (a
//! greatest fixed point and a hidden-name quantifier).
//!
//! [`RhoLogic`] hand-writes the instance for the rho calculus presented in
//! [`crate::syntax`]. That is honest for now — the generated logic is still
//! under development in the feature branch — provided it sits behind the
//! interface the generator will implement, which is DR-W4.

use crate::syntax::{Name, Term};

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum NamePred {
    /// This exact name.
    Exactly(Name),
    /// `n ⊨ @φ` iff `n = @P` with `P ⊨ φ`. Namespace logic: a namespace is
    /// described by a property rather than enumerated. Available only because
    /// names are quoted processes.
    Quote(Box<Formula>),
    Any,
}

/// How a modality quantifies over redex positions. This is what makes the
/// logic *context-labelled* rather than action-labelled: an action-labelled
/// logic sees one label where this one sees as many as there are enabled
/// interactions.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum PosQuant {
    Exists,
    Forall,
    /// Pin a position by its channel.
    At(String),
}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum Cmp {
    Ge,
    Le,
    Eq,
}

pub type FormulaVar = String;

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum Formula {
    Top,
    Bot,
    And(Box<Formula>, Box<Formula>),
    Or(Box<Formula>, Box<Formula>),
    Not(Box<Formula>),

    // ---- structural: one connective per term former ----
    /// Holds of `n!(Q)` with `Q ⊨ φ`.
    Out {
        chan: NamePred,
        body: Box<Formula>,
    },
    /// The analogue on receipts.
    In {
        chan: NamePred,
        body: Box<Formula>,
    },
    /// Separating conjunction: `P ⊨ φ ∣ ψ` iff `P ≡ Q ∣ R` with `Q ⊨ φ`,
    /// `R ⊨ ψ`. Generated by the associative--commutative equational theory of
    /// parallel composition; everything a modal logic cannot say is said here.
    Sep(Box<Formula>, Box<Formula>),
    Zero,
    /// The term is exactly this one, up to structural congruence. Cheap, and
    /// what makes a namespace predicate able to test a name's tag:
    /// `@(Eq(tag) ∣ ⊤)` describes every structured name carrying that tag.
    Eq(Term),
    /// The structural connective generated for the list former: the term is a
    /// list whose element at `index` satisfies `body`. This is what lets a name
    /// predicate *recover the indices* of a structured name, which is the whole
    /// point of namespace logic — in an atomic-name calculus the indices would
    /// have to travel as message payloads and the logic could reach them only
    /// by observing traffic.
    ListAt {
        index: usize,
        body: Box<Formula>,
    },

    /// Sugar for an `n`-fold separating conjunction of `Out(chan)⊤` — how many
    /// messages are pending on a channel. Kept primitive because the nested
    /// form is quadratic to check and this is linear.
    Count {
        chan: NamePred,
        cmp: Cmp,
        n: usize,
    },

    // ---- behavioural: the addition ----
    /// `⟨K_j⟩φ` — a step labelled by the position `j` after which `φ` holds.
    Dia {
        rule: crate::redex::RuleId,
        pos: PosQuant,
        body: Box<Formula>,
    },
    /// `[K_j]φ`.
    Boxm {
        rule: crate::redex::RuleId,
        pos: PosQuant,
        body: Box<Formula>,
    },

    // ---- additions to the template ----
    Nu {
        var: FormulaVar,
        body: Box<Formula>,
    },
    Var(FormulaVar),
}

impl Formula {
    pub fn and(a: Formula, b: Formula) -> Formula {
        Formula::And(Box::new(a), Box::new(b))
    }
    pub fn or(a: Formula, b: Formula) -> Formula {
        Formula::Or(Box::new(a), Box::new(b))
    }
    pub fn not(a: Formula) -> Formula {
        Formula::Not(Box::new(a))
    }
    pub fn sep(a: Formula, b: Formula) -> Formula {
        Formula::Sep(Box::new(a), Box::new(b))
    }
    pub fn out(chan: Name) -> Formula {
        Formula::Out {
            chan: NamePred::Exactly(chan),
            body: Box::new(Formula::Top),
        }
    }
    pub fn inn(chan: Name) -> Formula {
        Formula::In {
            chan: NamePred::Exactly(chan),
            body: Box::new(Formula::Top),
        }
    }
    /// `⟨K⟩φ` with the existential over positions — the common case.
    pub fn dia(body: Formula) -> Formula {
        Formula::Dia {
            rule: crate::redex::COMM,
            pos: PosQuant::Exists,
            body: Box::new(body),
        }
    }
    pub fn boxm(body: Formula) -> Formula {
        Formula::Boxm {
            rule: crate::redex::COMM,
            pos: PosQuant::Forall,
            body: Box::new(body),
        }
    }
    /// A namespace predicate: a communication redex on *any* channel whose
    /// name quotes a process carrying `tag`. One formula for a whole family of
    /// synapses, where a name-keyed presentation would need one key per channel
    /// and would have to be regenerated when the network grew.
    pub fn comm_in_namespace(tag: Term) -> Formula {
        Formula::comm_in_namespace_at(0, Formula::Eq(tag))
    }

    /// The general form: a communication redex on any channel whose name
    /// quotes a list whose `index`th element satisfies `body`. `index = 0`
    /// selects by tag; a later index selects by endpoint, so
    /// "every synapse onto neuron `i`" is one key rather than one per synapse.
    pub fn comm_in_namespace_at(index: usize, body: Formula) -> Formula {
        let np = NamePred::Quote(Box::new(Formula::ListAt {
            index,
            body: Box::new(body),
        }));
        Formula::sep(
            Formula::In {
                chan: np.clone(),
                body: Box::new(Formula::Top),
            },
            Formula::Out {
                chan: np,
                body: Box::new(Formula::Top),
            },
        )
    }

    /// The key shape of the note's §8: a communication redex on a channel.
    pub fn comm_on(chan: Name) -> Formula {
        Formula::sep(Formula::inn(chan.clone()), Formula::out(chan))
    }

    /// Structural depth (note, Definition 4). Modal formers do not contribute
    /// to structural depth; they are counted separately by [`Formula::modal_depth`].
    pub fn depth(&self) -> usize {
        match self {
            Formula::Top | Formula::Bot | Formula::Zero | Formula::Var(_) => 0,
            Formula::Eq(_) => 0,
            Formula::ListAt { body, .. } => 1 + body.depth(),
            Formula::Count { .. } => 1,
            Formula::Not(a) | Formula::Nu { body: a, .. } => a.depth(),
            Formula::And(a, b) | Formula::Or(a, b) => a.depth().max(b.depth()),
            Formula::Sep(a, b) => a.depth().max(b.depth()),
            Formula::Out { chan, body } | Formula::In { chan, body } => {
                1 + body.depth().max(name_depth(chan))
            }
            Formula::Dia { body, .. } | Formula::Boxm { body, .. } => body.depth(),
        }
    }

    /// Nesting of behavioural modalities. This is the quantity that costs
    /// exponentially, since each level enumerates all successors.
    pub fn modal_depth(&self) -> usize {
        match self {
            Formula::Top | Formula::Bot | Formula::Zero | Formula::Var(_) => 0,
            Formula::Eq(_) => 0,
            Formula::ListAt { body, .. } => body.modal_depth(),
            Formula::Count { .. } => 0,
            Formula::Not(a) | Formula::Nu { body: a, .. } => a.modal_depth(),
            Formula::And(a, b) | Formula::Or(a, b) | Formula::Sep(a, b) => {
                a.modal_depth().max(b.modal_depth())
            }
            Formula::Out { chan, body } | Formula::In { chan, body } => {
                body.modal_depth().max(name_modal_depth(chan))
            }
            Formula::Dia { body, .. } | Formula::Boxm { body, .. } => 1 + body.modal_depth(),
        }
    }

    pub fn has_fixpoint(&self) -> bool {
        match self {
            Formula::Nu { .. } => true,
            Formula::Top | Formula::Bot | Formula::Zero | Formula::Var(_) => false,
            Formula::Eq(_) => false,
            Formula::ListAt { body, .. } => body.has_fixpoint(),
            Formula::Count { .. } => false,
            Formula::Not(a) => a.has_fixpoint(),
            Formula::And(a, b) | Formula::Or(a, b) | Formula::Sep(a, b) => {
                a.has_fixpoint() || b.has_fixpoint()
            }
            Formula::Out { chan, body } | Formula::In { chan, body } => {
                body.has_fixpoint() || name_has_fixpoint(chan)
            }
            Formula::Dia { body, .. } | Formula::Boxm { body, .. } => body.has_fixpoint(),
        }
    }

    /// Whether a fixed-point variable occurs only positively, which
    /// Knaster--Tarski requires.
    pub fn positive_in(&self, var: &str, polarity: bool) -> bool {
        match self {
            Formula::Var(v) if v == var => polarity,
            Formula::Top | Formula::Bot | Formula::Zero | Formula::Var(_) => true,
            Formula::Eq(_) => true,
            Formula::ListAt { body, .. } => body.positive_in(var, polarity),
            Formula::Count { .. } => true,
            Formula::Not(a) => a.positive_in(var, !polarity),
            Formula::And(a, b) | Formula::Or(a, b) | Formula::Sep(a, b) => {
                a.positive_in(var, polarity) && b.positive_in(var, polarity)
            }
            Formula::Out { body, .. } | Formula::In { body, .. } => body.positive_in(var, polarity),
            Formula::Dia { body, .. } | Formula::Boxm { body, .. } => {
                body.positive_in(var, polarity)
            }
            Formula::Nu { body, var: v } => {
                if v == var {
                    true
                } else {
                    body.positive_in(var, polarity)
                }
            }
        }
    }

    /// See the free function [`nonstructural_at`]; requirement (R3).
    pub fn nonstructural_at(&self) -> Option<String> {
        nonstructural_at(self)
    }

    /// Whether the formula lies in the structural fragment, hence whether it is
    /// admissible as a refinement key.
    pub fn is_structural(&self) -> bool {
        self.nonstructural_at().is_none()
    }

    pub fn render(&self) -> String {
        match self {
            Formula::Top => "T".into(),
            Formula::Bot => "F".into(),
            Formula::Zero => "0".into(),
            Formula::Eq(t) => format!("={}", t.render()),
            Formula::ListAt { index, body } => format!("[{}]{}", index, body.render()),
            Formula::Var(v) => v.clone(),
            Formula::And(a, b) => format!("({} & {})", a.render(), b.render()),
            Formula::Or(a, b) => format!("({} | {})", a.render(), b.render()),
            Formula::Not(a) => format!("~{}", a.render()),
            Formula::Sep(a, b) => format!("({} ∣ {})", a.render(), b.render()),
            Formula::Out { chan, body } => format!("out({}){}", render_np(chan), body.render()),
            Formula::In { chan, body } => format!("in({}){}", render_np(chan), body.render()),
            Formula::Count { chan, cmp, n } => format!(
                "#{}{}{}",
                render_np(chan),
                match cmp {
                    Cmp::Ge => ">=",
                    Cmp::Le => "<=",
                    Cmp::Eq => "==",
                },
                n
            ),
            Formula::Dia { pos, body, .. } => format!("<K{}>{}", render_pos(pos), body.render()),
            Formula::Boxm { pos, body, .. } => format!("[K{}]{}", render_pos(pos), body.render()),
            Formula::Nu { var, body } => format!("nu {}.{}", var, body.render()),
        }
    }
}

fn render_np(n: &NamePred) -> String {
    match n {
        NamePred::Exactly(nm) => nm.key(),
        NamePred::Quote(f) => format!("@{}", f.render()),
        NamePred::Any => "_".into(),
    }
}

fn render_pos(p: &PosQuant) -> String {
    match p {
        PosQuant::Exists => "".into(),
        PosQuant::Forall => "".into(),
        PosQuant::At(c) => format!("@{c}"),
    }
}

fn name_depth(n: &NamePred) -> usize {
    match n {
        NamePred::Quote(f) => f.depth(),
        _ => 0,
    }
}
fn name_modal_depth(n: &NamePred) -> usize {
    match n {
        NamePred::Quote(f) => f.modal_depth(),
        _ => 0,
    }
}
fn name_has_fixpoint(n: &NamePred) -> bool {
    match n {
        NamePred::Quote(f) => f.has_fixpoint(),
        _ => false,
    }
}

// ---------------------------------------------------------------------------
// Budgets and the ideal / checkable split
// ---------------------------------------------------------------------------

/// The note's methodological commitment made into a type: the *ideal* logic
/// defines, restricted *fragments* decide. A logic whose model checking
/// terminates is necessarily not adequate for the whole of a Turing-complete
/// host, so the restriction is not a compromise but the price of executability.
#[derive(Clone, Copy, Debug)]
pub struct Budget {
    pub modal_depth: u8,
    pub inference_tokens: u64,
    pub states: u32,
}

impl Default for Budget {
    fn default() -> Self {
        Budget {
            modal_depth: 3,
            inference_tokens: 1_000_000,
            states: 100_000,
        }
    }
}

impl Budget {
    pub fn spend(&mut self, n: u64) -> Result<(), CheckError> {
        if self.inference_tokens < n {
            self.inference_tokens = 0;
            return Err(CheckError::BudgetExhausted);
        }
        self.inference_tokens -= n;
        Ok(())
    }
}

#[derive(Clone, PartialEq, Eq, Debug)]
pub enum CheckError {
    BudgetExhausted,
    StateSpaceExceeded,
    UnboundVariable(String),
}

/// Why a formula was refused as a key. Diagnostics name the offending
/// subformula: a modeller who writes an unbounded key should get a message, not
/// a hung simulation.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum WhyNot {
    TooDeep { got: usize, budget: u8, at: String },
    UnboundedFixpoint { at: String },
    NegativeFixpointVariable { var: String, at: String },
    /// The formula leaves the structural fragment, so it may be a *property*
    /// but not a *key*. See [`Checkable::try_key`] and requirement (R3).
    NotStructural { at: String },
}

impl std::fmt::Display for WhyNot {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WhyNot::TooDeep { got, budget, at } => write!(
                f,
                "modal depth {got} exceeds budget {budget}, in subformula `{at}`"
            ),
            WhyNot::UnboundedFixpoint { at } => write!(
                f,
                "greatest fixed point requires a known-finite reachable set, in `{at}`"
            ),
            WhyNot::NegativeFixpointVariable { var, at } => write!(
                f,
                "fixed-point variable `{var}` occurs negatively, in `{at}`"
            ),
            WhyNot::NotStructural { at } => write!(
                f,
                "`{at}` is outside the structural fragment, so it cannot be a key: \
                 a rate that depends on what a redex can do next cannot be recomputed \
                 locally when something elsewhere in the term changes. It remains \
                 usable as a property"
            ),
        }
    }
}

/// A formula admitted to a checkable fragment. Key sets are `Checkable`;
/// post-hoc properties need not be.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Checkable(Formula);

impl Checkable {
    /// Admit a formula as a **property**: bounded modal depth, no fixed point
    /// over an unknown-finite state space, no negative fixed-point variable.
    /// Modalities and `ν` are permitted.
    ///
    /// Use [`Checkable::try_key`] for a refinement key, which is strictly
    /// stronger.
    pub fn try_new(f: Formula, b: &Budget, finite_state_space: bool) -> Result<Checkable, WhyNot> {
        let md = f.modal_depth();
        if md > b.modal_depth as usize {
            return Err(WhyNot::TooDeep {
                got: md,
                budget: b.modal_depth,
                at: f.render(),
            });
        }
        if f.has_fixpoint() && !finite_state_space {
            return Err(WhyNot::UnboundedFixpoint { at: f.render() });
        }
        if let Some(bad) = negative_fixpoint_var(&f) {
            return Err(WhyNot::NegativeFixpointVariable {
                var: bad,
                at: f.render(),
            });
        }
        Ok(Checkable(f))
    }

    /// Admit a formula as a **refinement key**.
    ///
    /// Everything [`Checkable::try_new`] requires, plus requirement (R3),
    /// *structurality*: a key must lie in the structural fragment. This is not
    /// a matter of taste. The locality lemma the incremental propensity scheme
    /// rests on is true of the structural fragment and false of the logic as a
    /// whole: `⟨K_j⟩φ` inspects the *successors* of a term rather than a bounded
    /// syntactic neighbourhood of a position, and a greatest fixed point may be
    /// refuted only by unbounded inspection, so neither is confined by a depth
    /// bound. Admitting them as keys silently costs a global reclassification
    /// at every step — which is what an earlier version of this crate did,
    /// while the note claimed locality for keys in general.
    ///
    /// The restriction is on keys alone. Modalities and `ν` remain available
    /// for stating and checking properties of the resulting chain.
    pub fn try_key(f: Formula, b: &Budget, finite_state_space: bool) -> Result<Checkable, WhyNot> {
        if let Some(at) = f.nonstructural_at() {
            return Err(WhyNot::NotStructural { at });
        }
        Checkable::try_new(f, b, finite_state_space)
    }

    /// Escape hatch for formulae whose checkability is guaranteed by
    /// construction (depth-2 channel predicates, for instance).
    ///
    /// This bypasses (R3) as well, so prefer [`Checkable::trusted_key`] when the
    /// formula is destined for a key set; the partition builder applies (R3)
    /// regardless, so a modal key cannot reach a theory by this route either.
    pub fn trusted(f: Formula) -> Checkable {
        Checkable(f)
    }

    /// As [`Checkable::trusted`], but refuses a non-structural formula. Cheap:
    /// a syntactic walk, no satisfaction checking.
    pub fn trusted_key(f: Formula) -> Result<Checkable, WhyNot> {
        match f.nonstructural_at() {
            Some(at) => Err(WhyNot::NotStructural { at }),
            None => Ok(Checkable(f)),
        }
    }

    pub fn formula(&self) -> &Formula {
        &self.0
    }

    pub fn render(&self) -> String {
        self.0.render()
    }
}

/// The first subformula outside the **structural fragment**, rendered, or
/// `None` if there is none.
///
/// The structural fragment is one connective per term former — `out`, `in`,
/// `@`, the separating conjunction, `Zero`, `Eq`, `ListAt`, `Count` — together
/// with the propositional connectives. Outside it lie the behavioural
/// modalities `⟨K_j⟩` and `[K_j]`, the greatest fixed point, and fixed-point
/// variables.
///
/// The line is drawn where the locality lemma stops holding, not where the
/// logic stops being interesting: every connective here is satisfied or refuted
/// by inspecting a bounded neighbourhood of a position in the term, and every
/// connective excluded is not.
pub fn nonstructural_at(f: &Formula) -> Option<String> {
    match f {
        Formula::Dia { .. } | Formula::Boxm { .. } | Formula::Nu { .. } | Formula::Var(_) => {
            Some(f.render())
        }
        Formula::And(a, b) | Formula::Or(a, b) | Formula::Sep(a, b) => {
            nonstructural_at(a).or_else(|| nonstructural_at(b))
        }
        Formula::Not(a) => nonstructural_at(a),
        Formula::Out { chan, body } | Formula::In { chan, body } => {
            namepred_nonstructural(chan).or_else(|| nonstructural_at(body))
        }
        Formula::Count { chan, .. } => namepred_nonstructural(chan),
        Formula::ListAt { body, .. } => nonstructural_at(body),
        Formula::Top | Formula::Bot | Formula::Zero | Formula::Eq(_) => None,
    }
}

fn namepred_nonstructural(p: &NamePred) -> Option<String> {
    match p {
        NamePred::Quote(f) => nonstructural_at(f),
        NamePred::Exactly(_) | NamePred::Any => None,
    }
}

fn negative_fixpoint_var(f: &Formula) -> Option<String> {
    match f {
        Formula::Nu { var, body } => {
            if !body.positive_in(var, true) {
                Some(var.clone())
            } else {
                negative_fixpoint_var(body)
            }
        }
        Formula::Not(a) => negative_fixpoint_var(a),
        Formula::And(a, b) | Formula::Or(a, b) | Formula::Sep(a, b) => {
            negative_fixpoint_var(a).or_else(|| negative_fixpoint_var(b))
        }
        Formula::Out { body, .. }
        | Formula::In { body, .. }
        | Formula::Dia { body, .. }
        | Formula::Boxm { body, .. } => negative_fixpoint_var(body),
        _ => None,
    }
}

/// Convenience: `⊨` on the term level, exposed for tests.
pub fn term_is_zero(t: &Term) -> bool {
    matches!(t.canonical(), Term::Zero)
}
